In [11]:
import numpy as np
import matplotlib.pyplot as plt

# Define the function f(x) = x * sin(3x) - exp(x)
def f(x):
    return x * np.sin(3 * x) - np.exp(x)

# Define the derivative f'(x)
def f_prime(x):
    return np.sin(3 * x) + 3 * x * np.cos(3 * x) - np.exp(x)

# Newton-Raphson method implementation
def newton_raphson(x0, tol=1e-6, max_iter=1000):
    x_values = []
    x_n = x0
    x_values.append(x_n)
    
    for i in range(max_iter):
        f_xn = f(x_n)
        f_prime_xn = f_prime(x_n)
        if f_prime_xn == 0:
            raise ValueError("Derivative is zero, Newton-Raphson cannot proceed.")
        
        # Newton-Raphson update
        x_n = x_n - f_xn / f_prime_xn
        x_values.append(x_n)  # Append the new x_n value
        if abs(f_xn) < tol:  # Check if we have converged
            break

    return x_values, i + 1

# Bisection method implementation
def bisection_method(a, b, tol=1e-6):
    fa, fb = f(a), f(b)
    if fa * fb > 0:
        raise ValueError("The function must have opposite signs at the endpoints a and b.")
    
    midpoint_values = []
    iterations = 0
    while (b - a) / 2 > tol:
        midpoint = (a + b) / 2
        midpoint_values.append(midpoint)
        fmid = f(midpoint)
       
        if abs(fmid) < tol:
            return midpoint_values, len(midpoint_values)
        
        if fa * fmid < 0:
            b = midpoint
        else:
            a = midpoint
            fa = fmid
        iterations += 1
        
    
    return midpoint_values, iterations + 1

# Initial guess for Newton-Raphson
x0_newton = -1.6
A1, iter_newton = newton_raphson(x0_newton)

# Endpoints for Bisection Method
a_bisect, b_bisect = -0.7, -0.4
A2, iter_bisect = bisection_method(a_bisect, b_bisect)

# A3 is a vector with the number of iterations for Newton and Bisection respectively
A3 = [iter_newton, iter_bisect]

# Print results
print("A1 (Newton-Raphson x-values):", A1)
print("A2 (Bisection midpoints):", A2)
print("A3 (Number of iterations for Newton and Bisection):", A3)

# Plot results

# Creating a range of x values for the function plot
x_vals = np.linspace(-2, 0.5, 400)
y_vals = f(x_vals)

# Create the figure and subplots
fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(10, 12))

# Plot the function and Newton-Raphson iterations on the first subplot
ax1.plot(x_vals, y_vals, label=r'$f(x) = x \sin(3x) - \exp(x)$', color='blue')
ax1.plot(A1, [f(x) for x in A1], 'ro', label="Newton-Raphson Iterations")
ax1.set_title('Newton-Raphson Method Convergence')
ax1.set_xlabel('x')
ax1.set_ylabel('f(x)')
ax1.legend(loc='upper right')
ax1.grid(True)

# Plot the function and Bisection midpoints on the second subplot
ax2.plot(x_vals, y_vals, label=r'$f(x) = x \sin(3x) - \exp(x)$', color='blue')
ax2.plot(A2, [f(x) for x in A2], 'go', label="Bisection Midpoints")
ax2.set_title('Bisection Method Midpoints')
ax2.set_xlabel('x')
ax2.set_ylabel('f(x)')
ax2.legend(loc='upper right')
ax2.grid(True)

# Show the plot
plt.tight_layout()
plt.show()

A1 (Newton-Raphson x-values): [-1.6, np.float64(3.1979951385210694), np.float64(2.4644024441424284), np.float64(1.2035359007112925), np.float64(0.6502014632644292), np.float64(-0.1169233418248703), np.float64(-0.6605234854521386), np.float64(-0.5219265439062168), np.float64(-0.5665527428708069), np.float64(-0.5707465821813341), np.float64(-0.57078961788788), np.float64(-0.57078962246829)]
A2 (Bisection midpoints): [-0.55, -0.625, -0.5875, -0.5687500000000001, -0.578125, -0.5734375, -0.5710937500000001, -0.5699218750000001, -0.5705078125, -0.57080078125, -0.570654296875, -0.5707275390625, -0.57076416015625, -0.570782470703125, -0.5707916259765625, -0.5707870483398438, -0.5707893371582031]
A3 (Number of iterations for Newton and Bisection): [11, 17]


In [12]:
import numpy as np

# Define matrices and vectors
A = np.array([[1, 2], [-1, 1]])
B = np.array([[2, 0], [0, 2]])
C = np.array([[2, 0, -3], [0, 0, -1]])
D = np.array([[1, 2], [2, 3], [-1, 0]])
x = np.array([1, 0])
y = np.array([0, 1])
z = np.array([1, 2, -1])

# Calculate (a) A + B
A4 = A + B

# Calculate (b) 3x - 4y
A5 = 3 * x - 4 * y

# Calculate (c) Ax
A6 = np.dot(A, x)

# Calculate (d) B(x - y)
A7 = np.dot(B, x - y)

# Calculate (e) D x
A8 = np.dot(D, x)

# Calculate (f) D y + z
A9 = np.dot(D, y) + z

# Calculate (g) AB
A10 = np.dot(A, B)

# Calculate (h) BC
A11 = np.dot(B, C)

# Calculate (i) CD
A12 = np.dot(C, D)

A4, A5, A6, A7, A8, A9, A10, A11, A12


(array([[ 3,  2],
        [-1,  3]]),
 array([ 3, -4]),
 array([ 1, -1]),
 array([ 2, -2]),
 array([ 1,  2, -1]),
 array([ 3,  5, -1]),
 array([[ 2,  4],
        [-2,  2]]),
 array([[ 4,  0, -6],
        [ 0,  0, -2]]),
 array([[5, 4],
        [1, 0]]))